'use client';

import Link from 'next/link';
import { useState, useEffect } from 'react';

interface HighScore {
  score: number;
  difficulty: string;
  date: string;
}

export default function HomePage() {
  const [highScores, setHighScores] = useState<HighScore[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [greeting, setGreeting] = useState('');

  // Set time-based greeting
  useEffect(() => {
    const hour = new Date().getHours();
    if (hour < 12) {
      setGreeting('Good Morning! 🌅');
    } else if (hour < 17) {
      setGreeting('Good Afternoon! ☀️');
    } else {
      setGreeting('Good Evening! 🌙');
    }
  }, []);

  // Fetch high scores
  useEffect(() => {
  const fetchHighScores = async () => {
    try {
      const response = await fetch('/api/high-scores');
      if (response.ok) {
        const data = await response.json();
        if (Array.isArray(data)) {
          setHighScores(data.slice(0, 3)); // Only take top 3
        }
      }
    } catch (error) {
      console.error('Error fetching high scores:', error);
      setHighScores([]); // Fallback to empty array
    }
  };    fetchHighScores();
  }, []);
  const features = [
    {
      icon: '🤖',
      title: 'AI-Powered Problems',
      description: 'Dynamic math problems generated by Google Gemini AI for endless practice'
    },
    {
      icon: '🎯',
      title: 'Multiple Difficulty Levels',
      description: 'Beginner, Intermediate, Advanced, and Expert levels with increasing challenges'
    },
    {
      icon: '⏱️',
      title: 'Timed Challenges',
      description: 'Time-based problems to improve speed and accuracy under pressure'
    },
    {
      icon: '🏆',
      title: 'Score Tracking',
      description: 'Track your progress with detailed scoring and leaderboard rankings'
    },
    {
      icon: '�',
      title: 'Problem History',
      description: 'Review your recent attempts with detailed feedback and performance insights'
    },
    {
      icon: '🎮',
      title: 'Gamified Learning',
      description: 'Fun and engaging interface that makes math practice enjoyable'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-sm border-b border-gray-200 sticky top-0 z-40">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-indigo-600 text-white p-2 rounded-lg">
                <span className="text-xl font-bold">📚</span>
              </div>
              <h1 className="text-xl font-bold text-gray-800">Math Problem Generator</h1>
            </div>
            <Link
              href="/quiz"
              className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
            >
              Start Quiz
            </Link>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8 max-w-6xl">
        {/* Hero Section */}
        <section className="text-center mb-12">
          <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
            <h2 className="text-2xl md:text-3xl font-bold text-gray-800 mb-4">
              {greeting}
            </h2>
            <p className="text-lg text-gray-600 mb-6 max-w-2xl mx-auto">
              Welcome to the ultimate AI-powered math practice platform!
              Challenge yourself with dynamic problems designed for Primary 5 students,
              compete for high scores, and improve your mathematical skills.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/quiz"
                className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-4 rounded-xl font-bold text-lg transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg"
              >
                🚀 Start Practicing Now
              </Link>
              <Link
                href="/history"
                className="bg-purple-600 hover:bg-purple-700 text-white px-8 py-4 rounded-xl font-bold text-lg transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg"
              >
                📜 View History
              </Link>
              <button
                onClick={() => window.scrollTo({ top: document.getElementById('features')?.offsetTop, behavior: 'smooth' })}
                className="bg-white hover:bg-gray-50 text-indigo-600 border-2 border-indigo-600 px-8 py-4 rounded-xl font-bold text-lg transition-all duration-300"
              >
                📋 Learn More
              </button>
            </div>
          </div>
        </section>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Features Section */}
          <section id="features" className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-xl p-6 md:p-8">
              <h3 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
                <span className="bg-indigo-100 p-2 rounded-lg mr-3">⭐</span>
                Platform Features
              </h3>
              <div className="grid md:grid-cols-2 gap-6">
                {features.map((feature, index) => (
                  <div
                    key={index}
                    className="flex items-start space-x-4 p-4 rounded-xl bg-gray-50 hover:bg-indigo-50 transition-colors duration-200"
                  >
                    <div className="text-2xl">{feature.icon}</div>
                    <div>
                      <h4 className="font-semibold text-gray-800 mb-1">{feature.title}</h4>
                      <p className="text-sm text-gray-600">{feature.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* High Scores Section */}
          <section className="lg:col-span-1">
            <div className="bg-white rounded-2xl shadow-xl p-6 md:p-8">
              <h3 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
                <span className="bg-yellow-100 p-2 rounded-lg mr-3">🏆</span>
                High Scores
              </h3>

              {isLoading ? (
                <div className="space-y-3">
                  {[1, 2, 3].map((i) => (
                    <div key={i} className="animate-pulse">
                      <div className="h-12 bg-gray-200 rounded-lg"></div>
                    </div>
                  ))}
                </div>
              ) : highScores.length > 0 ? (
                <div className="space-y-3">
                  {highScores.slice(0, 3).map((score, index) => (
                    <div
                      key={index}
                      className={`flex items-center justify-between p-3 rounded-lg ${
                        index === 0
                          ? "bg-gradient-to-r from-yellow-100 to-yellow-200 border border-yellow-300"
                          : index === 1
                          ? "bg-gradient-to-r from-gray-100 to-gray-200 border border-gray-300"
                          : index === 2
                          ? "bg-gradient-to-r from-orange-100 to-orange-200 border border-orange-300"
                          : "bg-gray-50"
                      }`}
                    >
                      <div className="flex items-center space-x-3">
                        <span className="font-bold text-lg">
                          {index === 0 ? "🥇" : index === 1 ? "🥈" : index === 2 ? "🥉" : `#${index + 1}`}
                        </span>
                        <div>
                          <div className="font-semibold text-gray-800">{score.score} pts</div>
                          <div className="text-xs text-gray-600">{score.difficulty}</div>
                        </div>
                      </div>
                      <div className="text-xs text-gray-500">{score.date}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <div className="text-4xl mb-4">🎯</div>
                  <p className="text-gray-600 mb-4">No high scores yet!</p>
                  <p className="text-sm text-gray-500">Be the first to set a record.</p>
                </div>
              )}

              <div className="mt-6 pt-4 border-t border-gray-200">
                <Link
                  href="/quiz"
                  className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white py-3 px-4 rounded-lg font-medium transition-all duration-300 text-center block"
                >
                  🎮 Challenge the Leaderboard
                </Link>
              </div>
            </div>
          </section>
        </div>

        {/* Stats Section */}
        <section className="mt-12">
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl shadow-xl p-8 text-white text-center">
            <h3 className="text-2xl font-bold mb-4">Ready to Excel in Mathematics?</h3>
            <p className="text-lg mb-6 opacity-90">
              Join thousands of students improving their math skills with our AI-powered platform
            </p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-8">
              <div>
                <div className="text-3xl font-bold">1000+</div>
                <div className="text-sm opacity-80">Problems Generated</div>
              </div>
              <div>
                <div className="text-3xl font-bold">4</div>
                <div className="text-sm opacity-80">Difficulty Levels</div>
              </div>
              <div>
                <div className="text-3xl font-bold">24/7</div>
                <div className="text-sm opacity-80">Available</div>
              </div>
              <div>
                <div className="text-3xl font-bold">100%</div>
                <div className="text-sm opacity-80">Free to Use</div>
              </div>
            </div>
            <Link
              href="/quiz"
              className="bg-white text-indigo-600 hover:bg-gray-100 px-8 py-4 rounded-xl font-bold text-lg transition-all duration-300 transform hover:-translate-y-1 inline-block"
            >
              Start Your Math Journey 🚀
            </Link>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-gray-200 mt-16">
        <div className="container mx-auto px-4 py-8 text-center">
          <p className="text-gray-600">
            This is an assessment project • Built with Next.js & Google Gemini AI
          </p>
        </div>
      </footer>
    </div>
  );
}
